### PR TITLE
Bump to latest stable faker release

### PR DESCRIPTION
**Pull request by jmeyo**
released on june 2014

### CODE REVIEW

**Comment by willdurand** [comment]
This is pointless since composer already installs the latest version thanks to the `~` operator.

**Comment by willdurand** [comment]
Thanks for your contribution though

**Comment by jmeyo** [comment]
Well, somehow I wanted to use swiftBicNumber and it was not present, so I thought it was because of that, but indeed, that might comes from elsewhere.

**Comment by willdurand** [comment]
@jmeyo run `composer update`, it should help :)

**Comment by jmeyo** [comment]
ok, no need to be sarcastic. In any case, always better to restrain constraint resolution from composer, considering faker is simple and stable. Anyway..

**Comment by willdurand** [comment]
ahm, I am sorry, I didn't want to be "sarcastic". It was just a hint to help you fix your issue...

**Pull request closed without merging**
